name: Publish Docker images
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get Latest Tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1.0.1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and Push to frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          tags: ghcr.io/jontze/housefrontend:${{ steps.latesttag.outputs.tag }}, ghcr.io/jontze/housefrontend:latest
          push: true
      - name: Build and Push to backend image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          tags: ghcr.io/jontze/housebackend:${{ steps.latesttag.outputs.tag }}, ghcr.io/jontze/housebackend:latest
          push: true
